version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.11.1
    working_directory: ~/repo
    steps:
      - checkout
      - add_ssh_keys: # add SSH key with write access
          fingerprints:
            - "22:16:ff:36:4f:c9:89:7b:c4:de:4e:c8:41:16:d6:86"
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Publish update to GitHub
          command: bash ./deploy.sh
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: test
